Repository Metatavu/muisti-management, pull requests merged in 2020-08, with the labels that each got.

#197 Feature 196 content map
  src/components/app.tsx
  src/components/floor-plan/floor-plan-editor-view.tsx
  src/components/generic/card/card-item.tsx
  src/components/generic/content-map.tsx
  src/components/generic/spaces-map.tsx
  src/components/generic/top-bar.tsx
  src/components/screens/floor-plan-screen.tsx
  src/components/screens/group-content-versions-screen.tsx
  src/constants/actionTypes.ts
  src/localization/en.json
  src/localization/fi.json
  src/localization/strings.ts
  src/store/index.ts
Labels: enhancement

#213 Fixed sublayout property editing problem
  src/components/layout/editor-components/layout-common-properties-editor.tsx
  src/components/layout/editor-components/layout-widget-specific-properties-editor.tsx
  src/components/layout/utils/tree-data-utils.ts
  src/components/screens/layout-screen.tsx
  src/components/screens/sub-layout-screen.tsx
Labels: bug

#217 Added confirmation dialog to layout property delete
  src/components/screens/layout-screen.tsx
  src/components/screens/sub-layout-screen.tsx
Labels: enhancement

#225 Added component for listing devices in timeline
  src/components/containers/access-token-refresh.tsx
  src/components/content-editor/timeline-devices-list.tsx
  src/components/generic/device-list.tsx
  src/components/screens/content-editor-screen.tsx
Labels: enhancement

#227 Added page listing to timeline
  package.json
  src/components/content-editor/timeline-devices-list.tsx
  src/components/content-editor/timeline-editor.tsx
  src/components/screens/content-editor-screen.tsx
  src/styles/components/content-editor/timeline-devices-list.ts
  src/styles/components/content-editor/timeline-editor.ts
  src/styles/content-editor-screen.ts
  src/styles/element-timeline-pane.ts
Labels: enhancement

#228 Feature 223 element listing
  src/components/content-editor/common-settings-editor.tsx
  src/components/content-editor/event-trigger-editor.tsx
  src/components/content-editor/page-transition-elements-editor.tsx
  src/components/content-editor/resource-editor.tsx
  src/components/content-editor/transitions-editor.tsx
  src/components/generic/card/card-item.tsx
  src/components/generic/device-list.tsx
  src/components/generic/editor-utility-bar.tsx
  src/components/generic/top-bar.tsx
  src/components/left-middle-panel-editors/page-settings-editor.tsx
  src/components/right-panel-editors/media-library.tsx
  src/components/screens/content-editor-screen.tsx
  src/components/screens/timeline-screen.tsx
  src/localization/en.json
  src/localization/fi.json
  src/localization/strings.ts
  src/styles/element-contents-pane.ts
  src/utils/resource-utils.ts
Labels: enhancement

#235 Layout editor: Multiple fixes and improvements
  src/components/layout/editor-components/generic-property-checkbox.tsx
  src/components/layout/editor-components/widget-editors/button-editor.tsx
  src/components/layout/editor-constants/keys.ts
  src/localization/en.json
  src/localization/fi.json
  src/localization/strings.ts
Labels: bug, enhancement

#237 Added support for editing multiple resources
  src/components/screens/content-editor-screen.tsx
  src/utils/resource-utils.ts
Labels: enhancement

#239 Changed free drag to ordered draggable list
  package-lock.json
  package.json
  src/components/content-editor/common-settings-editor.tsx
  src/components/content-editor/timeline-editor.tsx
  src/components/generic/breadcrumbs.tsx
  src/components/screens/content-editor-screen.tsx
  src/components/screens/content-versions-screen.tsx
  src/components/screens/group-content-versions-screen.tsx
  src/styles/components/content-editor/timeline-editor.ts
Labels: enhancement

#248 Added scripted button and fixed some styles
  src/components/content-editor/resource-editor.tsx
  src/components/screens/content-editor-screen.tsx
  src/localization/en.json
  src/localization/fi.json
  src/localization/strings.ts
Labels: enhancement

#251 Feature 249 support for adding pages in new timeline
  src/components/app.tsx
  src/components/floor-plan/floor-plan-editor-view.tsx
  src/components/generic/top-bar.tsx
  src/components/screens/content-editor-screen.tsx
  src/components/screens/content-versions-screen.tsx
  src/components/screens/device-model-screen.tsx
  src/components/screens/group-content-versions-screen.tsx
  src/components/screens/rooms-screen.tsx
  src/components/screens/timeline-screen.tsx
  src/localization/en.json
  src/localization/fi.json
  src/localization/strings.ts
Labels: enhancement

#253 Feature 252 assign device index page id automatically
  src/components/content-editor/timeline-editor.tsx
  src/components/screens/content-editor-screen.tsx
  src/localization/strings.ts
Labels: enhancement

#269 Added elevation property
  src/components/layout/editor-components/layout-common-properties-editor.tsx
  src/components/layout/editor-constants/keys.ts
  src/localization/en.json
  src/localization/fi.json
  src/localization/strings.ts
Labels: enhancement

#273 Feature 270 layout editor selected tab indicator height property support
  src/components/layout/editor-components/layout-common-properties-editor.tsx
  src/components/layout/editor-components/widget-editors/tab-layout-editor.tsx
  src/components/layout/editor-constants/keys.ts
  src/localization/en.json
  src/localization/fi.json
  src/localization/strings.ts
Labels: enhancement

#276 Fixed page delete and add
  README.md
  package.json
  src/components/layout/layout-tree-menu.tsx
  src/components/screens/content-editor-screen.tsx
Labels: bug

#280 Video preview is visible and has controls now
  src/components/preview/components/page-preview-player-view.tsx
  src/components/preview/page-preview.tsx
Labels: enhancement

#278 Picker now closes when clicked outside of it
  package-lock.json
  src/components/layout/editor-components/color-picker.tsx
  src/components/layout/editor-components/layout-common-properties-editor.tsx
  src/components/layout/editor-components/margin-padding-editor.tsx
  src/components/layout/editor-components/widget-editors/button-editor.tsx
  src/components/layout/editor-components/widget-editors/flow-text-view-editor.tsx
  src/components/layout/editor-components/widget-editors/tab-layout-editor.tsx
  src/components/layout/editor-components/widget-editors/text-view-editor.tsx
  src/styles/common-properties-editor.ts
  src/styles/components/generic/color-picker.ts
Labels: bug
